### ISSUE TITLE
Can you explain how to use it?

### ISSUE THREAD

**Issue by minsy93** [ethanhann/Laravel-RediSearch#1]
I need this feature 
Thank you .

**Comment by ethanhann** [comment]
You set the driver in config/scout.php to "ehann-redisearch" and register the RediSearchScoutServiceProvider provider in config/app.php. 

Please be aware that this is an experimental package and might not even be compatible with the current version of RediSearch and RediSearch-PHP.

**Comment by minsy93** [comment]
Ok
Thank you

**Comment by ethanhann** [comment]
@SamHz The [import command](https://github.com/ethanhann/Laravel-RediSearch/blob/master/src/Scout/Console/ImportCommand.php#L61) in this package can be modified to allow for [batch indexing](www.ethanhann.com/redisearch-php/indexing/#batch-indexing). Feel free to submit a PR.
